version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - zip fcz-dev-api-proxy.zip nginx.conf
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  name: fcz-dev-api-${AWS_REGION}-proxy.zip
